repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ '--unsafe' ]
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./run-mypy.sh
        language: python
        types: [ python ]
        additional_dependencies: [ "mypy==0.910" ]
        require_serial: true
        verbose: true

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: make test
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python
        exclude: ^src/vehicle_recommendations/proto

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^src/vehicle_recommendations/proto
